# variables effected by dataset
adapter_output_dim: 4
num_classes: 4

# variables not effected by dataset
name: 'None'
test_metrics_path: 'testing'
adversarial_training: True
adversarial_prob: 0.5
adversarial_step_size: 1
non_adversarial_target: False
lr: 0.0000316
swivels: 17  # 'all', 'ConfidNet'19
patience: 20
loss_fn: 'dice'
hausdorff_sigma: 1.6761