# variables effected by dataset
out_channels: 4
checkpoint_dir: pre-trained/monai-unets/
checkpoint_path: "" 
#../../pre-trained/monai-unets/pmri-siemens-11-27_26-11-2024.ckpt
# mnmv2-ge-11-01_26-11-2024
# mnmv2-siemens-10-41_26-11-2024
# mnmv2-philips-11-16_26-11-2024
# pmri-philips-18-24_26-11-2024
# pmri-siemens-11-27_26-11-2024

# variables not effected by dataset
n_filters_init: 32
depth: 4
spatial_dims: 2
in_channels: 1
num_res_units: 8
lr: 1e-3
patience: 5
norm: instance
hausdorff_sigma: 1.6761
dropout: 0.0

# infered
# channels: [n_filters_init * 2 ** i for i in range(depth)]
# strides: [2] * (depth - 1)
# binary_target: True if out_channels == 1 else False